global:
  scrape_interval:     15s
  evaluation_interval: 15s

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).

# Load and evaluate rules in this file every 'evaluation_interval' seconds.


# A scrape configuration containing exactly one endpoint to scrape.
scrape_configs:


  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['127.0.0.1:9090']
  
  - job_name: 'node'
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9100']
  
  - job_name: 'vm'
    scrape_interval: 10s
    static_configs:
    - targets: ['127.0.0.1:9100']



